sudo: required
dist: xenial
language: cpp
compiler:
  - gcc

service:
  - docker

notifications:
  email:
    on_success: always
    on_failure: always

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - ROS_REPO=ros
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPO="ros-shadow-fixed"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="melodic" ROS_REPO="ros-shadow-fixed"
    - ROS_DISTRO="melodic"

matrix:
  include:
    - language: python
      python: 3.7
      install: 
      - pip install -q catkin-lint rosdep
      - sudo $(which rosdep) init
      - rosdep update
      script: catkin_lint -W2 --explain .
      env: JOB="catkin_lint" ROS_DISTRO="kinetic"
  allow_failures:
    - env: ROS_DISTRO="kinetic"
    - env: ROS_DISTRO="melodic"
    - env: JOB="catkin_lint" ROS_DISTRO="kinetic"

install: git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script: source .ci_config/travis.sh

